# Generated by Django 4.2.16 on 2025-03-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0018_alter_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_codigo_barras',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_barras/'),
        ),
    ]
